### ISSUE TITLE
Blender 4.1 compatibility

### ISSUE THREAD

**Issue by wkunz50** [cgvirus/Easy-Surface-Deformer-Blender#2]
Hello,
Looks like a great addon, however, though it seemed to install fine it does not appear in the side bar or anywhere else as far as I can tell. Is it not compatible with Blender 4.1?

**Comment by cgvirus** [comment]
Yes, it's working fine in 4.1.
You need download the zip and install the zip directly.It will be shown in object mode>Tools(n panel).
https://github.com/cgvirus/Easy-Surface-Deformer-Blender/releases

**Comment by wkunz50** [comment]
Okay, I'm using the CleanPanels addon and finally figured it out. Thanks for replying.
Cheers
